pid {{ .DataDir }}/nginx.pid;
daemon off;
worker_processes auto;

error_log syslog:server=unix:/dev/log warn;

events {
    worker_connections 1024;
}

http {
    access_log syslog:server=unix:/dev/log;
    include {{ .AppDir }}/nginx/etc/nginx/mime.types;

    client_body_temp_path {{ .DataDir }}/nginx/client_body_temp;
    proxy_temp_path {{ .DataDir }}/nginx/proxy_temp;
    fastcgi_temp_path {{ .DataDir }}/nginx/fastcgi_temp;
    uwsgi_temp_path {{ .DataDir }}/nginx/uwsgi_temp;
    scgi_temp_path {{ .DataDir }}/nginx/scgi_temp;

    client_max_body_size 0;

    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        ''      https;
    }

    upstream filebrowser {
        server unix:{{ .Socket }};
    }

    server {
        listen unix:{{ .CommonDir }}/web.socket;

        set_real_ip_from unix:;
        server_name localhost;

        location / {
            proxy_pass http://filebrowser;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_redirect off;
            proxy_buffering off;
        }
    }
}
